services:
    dmishh.settings.settings_manager:
        class: Dmishh\SettingsBundle\Manager\MongoDB\SettingsManager
        arguments:
            - "@doctrine.odm.mongodb.document_manager"
            - "@dmishh.settings.serializer"
            - "%settings_manager.settings%"